setwd("~/Downloads")
install.packages("tidyverse")
install.packages("tidyverse")
install.packages("tidyverse")
install.packages("tidyverse")
install.packages("tidyverse")
library(tidyverse)
dd=read_csv("JASP data Attractiveness and gender influence on morality.csv")
View(dd)
?pivot_longer
d2=dd %>% mutate(participant=seq_along(`participant gender`))
d2=dd %>% mutate(participant=seq_along(`participant gender`)) %>% relocate(participant)
View(d2)
d2 %>% pivot_longer(cols=2:last_col())
d2 %>% pivot_longer(cols=3:last_col())
d3=d2 %>% pivot_longer(cols=3:last_col())
View(d3)
d3 <- d3 %>% mutate(attractiveness=str_split(name, pattern=" "))
d3 <- d3 %>% mutate(attractiveness=str_split(name, pattern=" ")[1])
str_split(d3$age)
str_split(d3$name)
str_split(d3$name, pattern= " ")
str_split(d3$name, pattern= " ")[[1]]
str_split(d3$name, pattern= " ")[[1]][1]
d3 <- d3 %>% mutate(attractiveness=str_split(d3$name, pattern= " ")[[1]][1])
View(d3)
d3 <- d3 %>% mutate(attractiveness=ifelse(name[1]=="u", "unattractive")
)
d3 <- d3 %>% mutate(attractiveness=ifelse(name[1]=="u", "unattractive", "attractive")
)
View(d3)
d3 <- d3 %>% mutate(attractiveness=ifelse(substr(name, 1 =="u"), "unattractive", "attractive"))
substr(d3$name, 1, 1)
d3 <- d3 %>% mutate(attractiveness=ifelse(substr(name, 1, 1) =="u"), "unattractive", "attractive"))
d3 <- d3 %>% mutate(attractiveness=ifelse(substr(name, 1, 1) =="u"), "unattractive", "attractive")
d3 <- d3 %>% mutate(attractiveness=ifelse(substr(name, 1, 1) =="u", "unattractive", "attractive"))
View(d3)
unique(d3$attractiveness)
d4 <- d3 %>% mutate(stimulus_gender = ifelse(str_split(name, " ")[[1]][1]="f", "female", "male"))
d4 <- d3 %>% mutate(stimulus_gender = ifelse(str_split(name, " ")[[1]][1]=="f", "female", "male"))
View(d4)
d4 <- d3 %>% mutate(stimulus_gender = ifelse(str_split(name, " ")[[1]][2]=="f", "female", "male"))
View(d4)
str_split(d4$name, " ")
str_split(d4$name, " ")[[1]]
str_split(d4$name, " ")[[1000]]
str_split(d4$name, " ")[[1000]][2]
d4 <- d3 %>% mutate(stimulus_gender = ifelse(str_split(d4$name, " ")[[]][2]=="f", "female", "male"))
d4 <- d3 %>% mutate(stimulus_gender = ifelse(str_split(name, " ")[[]][2]=="f", "female", "male"))
d4 <- d3 %>% mutate(stimulus_gender = ifelse(str_split(name, " ")[[1]][2]=="f", "female", "male"))
View(d4)
d4 <- d3 %>% mutate(stimulus_gender = str_detect(name, "female"))
Vierw(d4)
View(d4)
d4 <- d3 %>% mutate(stimulus_gender = ifelse(str_detect(name, "female"), "female"))
d4 <- d3 %>% mutate(stimulus_gender = ifelse(str_detect(name, "female"), "female", NA))
d4 <- d3 %>% mutate(stimulus_gender = ifelse(str_detect(name, "male"), "male", name))
View(d4)
d4 <- d3 %>%
mutate(stimulus_gender =
ifelse(
str_detect(name, "male"), "male",
ifelse(str_detect(name, "female"), "female", NA)))
View(d4)
d4 <- d3 %>%
mutate(stimulus_gender =
ifelse(
str_detect(name, "male"), "male", "female"))
View(d4)
d4 <- d3 %>% mutate(stimulus_gender = ifelse(str_detect(name, "male"), "male", "female"))
View(d4)
d4 <- d3 %>% mutate(stimulus_gender = ifelse(str_detect(name, "female"), "female", "male"))
View(d4)
d4 <- d4 %>% mutate(stimulus_gender = ifelse(str_detect(name, "F"), "female", stimulus_gender))
View(d4)
d4 <- d4 %>% mutate(scenario_present = ifelse(str_detect(name, "M"), "scenario_present", "rating"))
View(d4)
d5 = d4 %>% mutate(which_scenario = str_sub(name, -1, -1))
View(d5)
q()
